@startuml diagrammeLaby
title Chargement du diagramme

'''classes
class Labyrinthe
{
  +pj : Perso
  +murs : Boolean

  +{static} get suivant(x: int, y: int, action: String) : int[]
  +Labyrinthe(nom : String)
  +deplacerPerso(action : String)
  +etreFini() : Boolean
  +descriptionLaby() : String
  +choixNiveau(niveau : int) : void
  +getlengthY() : int
  +getLength() : int
  +getMur(x: int, y: int)
}

class LabyJeu
{
  -labyrinthe : Labyrinthe

  +getLabyrinthe() : Labyrinthe
  +LabyJeu()
  +update(secondes double), clavier Clavier)
  +init()
  +etreFini() : Boolean
}

interface Jeu
{
  +update(secondes : double, clavier : Clavier)
  +init()
  +etreFini() : Boolean
}

'''relations
Jeu <|.. LabyJeu
LabyJeu "1" --> "*" Labyrinthe : -labyrinthes

@enduml

@startuml  sequenceLaby

participant "m:main" as main
participant "labyrinthe:Labyrinthe" as labyrinthe
participant "file : File" as File

activate main
main -> labyrinthe : new Labyrinthe(nomFichier)
activate labyrinthe
labyrinthe -> File : new File(cheminFichier)
activate File

File --> labyrinthe : FileNotFoundException
labyrinthe -> File : new File(cheminFichierParDefaut)
File --> labyrinthe
deactivate File
labyrinthe --> main
main -> labyrinthe : choixNiveau(niveau)
labyrinthe --> main
main -> labyrinthe : descriptionLaby()
labyrinthe --> main : description
deactivate labyrinthe
deactivate main
@enduml
