@startuml

participant "labyrinthe : Labyrinthe" as laby
participant "passageSecret : PassageSecret" as secret
participant "labyDessin : LabyDessin" as dessin

laby -> laby : deplacerPero(action : String)



alt si c'est pas un mur, on effectue le deplacement

  alt si la case est d'instance PassageSecret



laby -> secret : interagir(laby : Labyrinthe, perso : Personnage)

activate secret

  end

end



secret --> laby



deactivate secret


laby -> dessin : dessinerJeu(jeu :Jeu, canvas Canvas)
activate dessin

dessin --> laby

deactivate dessin

@enduml